# Generated by Django 5.2.5 on 2025-08-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_doctor_options_doctor_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(blank=True, default=0, verbose_name='Стаж работы (лет)'),
        ),
    ]
