# Generated by Django 5.2.5 on 2025-08-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_service_options_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.CharField(choices=[('good', 'Хорошо'), ('bad', 'Плохо')], default='good', max_length=10, verbose_name='Оценка'),
        ),
    ]
