# Generated by Django 5.2.5 on 2025-09-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='message',
            field=models.TextField(verbose_name='Текст отзыв'),
        ),
    ]
